// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0yGYW0xgkBE9h18Pi0m0f7u262e-Nm40',
    appId: '1:434029164576:web:082540017ac0b151a9e445',
    messagingSenderId: '434029164576',
    projectId: 'gerentelojaonlinedc',
    authDomain: 'gerentelojaonlinedc.firebaseapp.com',
    storageBucket: 'gerentelojaonlinedc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmAj_GXssB044wXkzO2eJYNJeyHDJUENc',
    appId: '1:434029164576:android:4421cf409ee6af29a9e445',
    messagingSenderId: '434029164576',
    projectId: 'gerentelojaonlinedc',
    storageBucket: 'gerentelojaonlinedc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbXL_ZfIS1K2x_PyS6QZ9hX2cPrQEIhg',
    appId: '1:434029164576:ios:8213bbb6954b3551a9e445',
    messagingSenderId: '434029164576',
    projectId: 'gerentelojaonlinedc',
    storageBucket: 'gerentelojaonlinedc.appspot.com',
    iosBundleId: 'br.com.gerentelojaonlinedc.projectGerenteLojaOnlineDc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApbXL_ZfIS1K2x_PyS6QZ9hX2cPrQEIhg',
    appId: '1:434029164576:ios:7fcd4c3e5895d91ca9e445',
    messagingSenderId: '434029164576',
    projectId: 'gerentelojaonlinedc',
    storageBucket: 'gerentelojaonlinedc.appspot.com',
    iosBundleId: 'br.com.gerentelojaonlinedc.projectGerenteLojaOnlineDc.RunnerTests',
  );
}
