// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjyKgMR55Yo2bcdvNqKy7g4RkGBTxBnu8',
    appId: '1:946111201716:web:c1942f32ca13dba27bb2e1',
    messagingSenderId: '946111201716',
    projectId: 'chat-online-d96c7',
    authDomain: 'chat-online-d96c7.firebaseapp.com',
    storageBucket: 'chat-online-d96c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDweCZAHhmXKs9FtZknUT3alls6-l7x79M',
    appId: '1:946111201716:android:07bc1efbdf13c4707bb2e1',
    messagingSenderId: '946111201716',
    projectId: 'chat-online-d96c7',
    storageBucket: 'chat-online-d96c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbK55YB9qUMioheX3pauv54ryKUgARz2I',
    appId: '1:946111201716:ios:866a66affc9dcd1b7bb2e1',
    messagingSenderId: '946111201716',
    projectId: 'chat-online-d96c7',
    storageBucket: 'chat-online-d96c7.appspot.com',
    iosBundleId: 'com.example.appChatOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbK55YB9qUMioheX3pauv54ryKUgARz2I',
    appId: '1:946111201716:ios:5b4ee18f75b680f67bb2e1',
    messagingSenderId: '946111201716',
    projectId: 'chat-online-d96c7',
    storageBucket: 'chat-online-d96c7.appspot.com',
    iosBundleId: 'com.example.appChatOnline.RunnerTests',
  );
}
