// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHv3s2Izxtgx5LVX4z_Z7W69VXB05rTdE',
    appId: '1:526727743414:web:5735933d73a640b0ea6317',
    messagingSenderId: '526727743414',
    projectId: 'projeto-uber-cf7df',
    authDomain: 'projeto-uber-cf7df.firebaseapp.com',
    storageBucket: 'projeto-uber-cf7df.appspot.com',
    measurementId: 'G-GLHPEM1NLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZV49s1t-7UwnRrkZo_tczAip3TiBPUOA',
    appId: '1:526727743414:android:7795dc91de5207dfea6317',
    messagingSenderId: '526727743414',
    projectId: 'projeto-uber-cf7df',
    storageBucket: 'projeto-uber-cf7df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4SPhFqOGUACqyi3-DEM_GBbZAhhOG_LM',
    appId: '1:526727743414:ios:e9d82807d7ba5c8dea6317',
    messagingSenderId: '526727743414',
    projectId: 'projeto-uber-cf7df',
    storageBucket: 'projeto-uber-cf7df.appspot.com',
    iosClientId: '526727743414-atilm70uv4d21egd7oklslofsbaic3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoUber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4SPhFqOGUACqyi3-DEM_GBbZAhhOG_LM',
    appId: '1:526727743414:ios:b87af850d47c2633ea6317',
    messagingSenderId: '526727743414',
    projectId: 'projeto-uber-cf7df',
    storageBucket: 'projeto-uber-cf7df.appspot.com',
    iosClientId: '526727743414-r0g6853mak9gn6tpu9bn0tgb108e6cna.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoUber.RunnerTests',
  );
}
